"""Post-processing for atomistic and DFT calculation results."""

from .geometry import (
    CoordinationNeighbor,
    CoordinationResult,
    GeometryError,
    PeriodicImage,
    SiteAngleResult,
    SiteDistanceResult,
    SiteImage,
    SiteMapping,
    StructureComparisonResult,
    compare_structures,
    coordination_by_cutoff,
    site_angle,
    site_distance,
)
from .structure import AtomicStructure, StructureError
from .structure_scene import (
    Projection,
    StructureAtomStyle,
    StructureAtomVisual,
    StructureBondSpec,
    StructureBondStyle,
    StructureBondVisual,
    StructureCameraSpec,
    StructureCellStyle,
    StructureScene,
    StructureSceneError,
    build_structure_scene,
    default_element_color,
    default_element_radius_angstrom,
)

__all__ = [
    "AtomicStructure",
    "CoordinationNeighbor",
    "CoordinationResult",
    "GeometryError",
    "PeriodicImage",
    "Projection",
    "SiteAngleResult",
    "SiteDistanceResult",
    "SiteImage",
    "SiteMapping",
    "StructureAtomStyle",
    "StructureAtomVisual",
    "StructureBondSpec",
    "StructureBondStyle",
    "StructureBondVisual",
    "StructureCameraSpec",
    "StructureCellStyle",
    "StructureComparisonResult",
    "StructureError",
    "StructureScene",
    "StructureSceneError",
    "build_structure_scene",
    "compare_structures",
    "coordination_by_cutoff",
    "default_element_color",
    "default_element_radius_angstrom",
    "site_angle",
    "site_distance",
]
